In [1]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [5]:
pwd

'C:\\Users\\abelu\\Desktop\\Complete-Python-3-Bootcamp-master (1)'

In [16]:
df1=pd.read_csv('C:\\Users\\abelu\\Desktop\\Temp\\winequality_red.csv',sep=';')

In [17]:
df1.head()

   fixed acidity  volatile acidity  citric acid  residual sugar   ...       pH  sulphates  alcohol  quality
0            7.4              0.70         0.00             1.9   ...     3.51       0.56      9.4        5
1            7.8              0.88         0.00             2.6   ...     3.20       0.68      9.8        5
2            7.8              0.76         0.04             2.3   ...     3.26       0.65      9.8        5
3           11.2              0.28         0.56             1.9   ...     3.16       0.58      9.8        6
4            7.4              0.70         0.00             1.9   ...     3.51       0.56      9.4        5

[5 rows x 12 columns]

In [20]:
def rankit(df):
    df['alco_qual_rank'] = np.arange(len(df))+1
    return df

In [23]:
df1.sort_values('alcohol',ascending=False,inplace=True)
df1=df1.groupby('quality').apply(rankit)

In [25]:
df1.head()

      fixed acidity  volatile acidity  citric acid       ...        alcohol  quality  alco_qual_rank
652            15.9              0.36         0.65       ...           14.9        5               1
588             5.0              0.42         0.24       ...           14.0        8               1
142             5.2              0.34         0.00       ...           14.0        6               1
144             5.2              0.34         0.00       ...           14.0        6               2
1270            5.0              0.38         0.01       ...           14.0        6               3

[5 rows x 13 columns]

In [34]:
qualnum=df1['quality']
qualnum

(652     5
 588     8
 142     6
 144     6
 1270    6
 1269    8
 467     6
 821     7
 1114    6
 1228    7
 1132    7
 1477    7
 1475    7
 1126    6
 492     7
 484     6
 455     8
 378     6
 491     7
 1118    6
 910     6
 45      4
 1120    8
 198     7
 353     5
 395     7
 1287    5
 132     5
 131     5
 982     6
        ..
 567     6
 367     5
 500     6
 18      4
 463     5
 603     6
 459     3
 236     6
 102     6
 1533    5
 99      6
 593     5
 89      5
 239     6
 496     6
 238     6
 167     4
 235     6
 234     6
 601     6
 1434    6
 120     5
 1435    6
 1474    5
 1476    5
 371     6
 528     6
 1436    5
 544     6
 517     3
 Name: quality, Length: 1599, dtype: int64,
 <function sorted(iterable, /, *, key=None, reverse=False)>)

In [36]:
df1[df1.alco_qual_rank==1].head(len(qualnum))

     fixed acidity  volatile acidity  citric acid       ...        alcohol  quality  alco_qual_rank
652           15.9              0.36         0.65       ...           14.9        5               1
588            5.0              0.42         0.24       ...           14.0        8               1

[2 rows x 13 columns]

In [37]:
len(qualnum)

2

In [39]:
df1[df1.alco_qual_rank==1]

     fixed acidity  volatile acidity  citric acid       ...        alcohol  quality  alco_qual_rank
652           15.9              0.36         0.65       ...           14.9        5               1
588            5.0              0.42         0.24       ...           14.0        8               1
142            5.2              0.34         0.00       ...           14.0        6               1
821            4.9              0.42         0.00       ...           14.0        7               1
45             4.6              0.52         0.15       ...           13.1        4               1
899            8.3              1.02         0.02       ...           11.0        3               1

[6 rows x 13 columns]

In [40]:
df1

      fixed acidity  volatile acidity  citric acid       ...          alcohol  quality  alco_qual_rank
652            15.9             0.360         0.65       ...        14.900000        5               1
588             5.0             0.420         0.24       ...        14.000000        8               1
142             5.2             0.340         0.00       ...        14.000000        6               1
144             5.2             0.340         0.00       ...        14.000000        6               2
1270            5.0             0.380         0.01       ...        14.000000        6               3
1269            5.5             0.490         0.03       ...        14.000000        8               2
467             8.8             0.460         0.45       ...        14.000000        6               4
821             4.9             0.420         0.00       ...        14.000000        7               1
1114            5.0             0.400         0.50       ...        13.600000        6               5
1228            5.1             0.420         0.00       ...        13.600000        7               2
1132            7.4             0.360         0.34       ...        13.600000        7               3
1477            5.3             0.470         0.11       ...        13.600000        7               4
1475            5.3             0.470         0.11       ...        13.566667        7               5
1126            5.8             0.290         0.26       ...        13.500000        6               6
492             8.9             0.400         0.51       ...        13.400000        7               6
484            10.6             0.440         0.68       ...        13.400000        6               7
455            11.3             0.620         0.67       ...        13.400000        8               3
378            11.4             0.625         0.66       ...        13.300000        6               8
491             9.2             0.410         0.50       ...        13.300000        7               7
1118            7.1             0.390         0.12       ...        13.300000        6               9
910             9.3             0.380         0.48       ...        13.200000        6              10
45              4.6             0.520         0.15       ...        13.100000        4               1
1120            7.9             0.540         0.34       ...        13.100000        8               4
198             5.4             0.835         0.08       ...        13.000000        7               8
353            13.5             0.530         0.79       ...        13.000000        5               2
395            12.0             0.370         0.76       ...        13.000000        7               9
1287            8.0             0.600         0.08       ...        13.000000        5               3
132             5.6             0.500         0.09       ...        13.000000        5               4
131             5.6             0.500         0.09       ...        13.000000        5               5
982             7.3             0.520         0.32       ...        12.900000        6              11
...             ...               ...          ...       ...              ...      ...             ...
567             8.7             0.700         0.24       ...         9.000000        6             622
367            10.4             0.575         0.61       ...         9.000000        5             673
500             7.8             0.520         0.25       ...         9.000000        6             623
18              7.4             0.590         0.08       ...         9.000000        4              52
463             8.1             0.660         0.70       ...         9.000000        5             674
603            13.2             0.460         0.52       ...         9.000000        6             624
459            11.6             0.580         0.66       ...         9.000000        3               9
236             7.2             0.630         0.00       ...         9.000000        6             625
102             8.1             0.545         0.18       ...         9.000000        6             626
1533            8.0             0.390         0.30       ...         9.000000        5             675
99              8.1             0.545         0.18       ...         9.000000        6             627
593             9.9             0.490         0.58       ...         9.000000        5             676
89              7.0             0.620         0.08       ...         9.000000        5             677
239             8.2             1.000         0.09       ...         9.000000        6             628
496             7.8             0.520         0.25       ...         9.000000        6             629
238             7.2             0.630         0.00       ...         9.000000        6             630
167             7.3             0.550         0.03       ...         9.000000        4              53
235             7.2             0.630         0.00       ...         9.000000        6             631
234             8.2             1.000         0.09       ...         9.000000        6             632
601            13.2             0.460         0.52       ...         9.000000        6             633
1434           10.2             0.540         0.37       ...         9.000000        6             634
120             7.3             1.070         0.09       ...         9.000000        5             678
1435           10.2             0.540         0.37       ...         9.000000        6             635
1474            9.9             0.500         0.50       ...         8.800000        5             679
1476            9.9             0.500         0.50       ...         8.800000        5             680
371             7.9             0.240         0.40       ...         8.700000        6             636
528             8.2             0.420         0.49       ...         8.700000        6             637
1436           10.0             0.380         0.38       ...         8.500000        5             681
544            14.3             0.310         0.74       ...         8.400000        6             638
517            10.4             0.610         0.49       ...         8.400000        3              10

[1599 rows x 13 columns]